# Basic
title: Z O H O
subtitle: 记得早先少年时
welcome_message: <a href="https://z0h0.github.io/" target="_blank">this page</a>
description: 你来人间一趟，你要看看太阳， 和你的心上人，一起走在街上。
creator: <a href="http://z0h0.github.io">@z0h0</a>

url: "http://z0h0.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    #- {title: Links, description: My fellows, url: 'http://z0h0.github.io'}
    - {title: Pictures, description: ideal place, url: 'http://z0hp.github.io/photopage.html'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment: true
comment:
    disqus: zachary-1
    # uyan: 2148612
    # duoshuo: 
    
# Social
social:
    weibo: zacharypt
    github: zacharypt
    twitter: zacharypt
    gplus: 107108267983477358170
    mail: zacharypt@zacharypt.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
